[package]
name = "clusterctl"
version = "0.3.0"
authors = ["Paperless Infra <infra@paperlesspost.com>"]
edition = "2018"

[dependencies]
dialoguer = "0.5.0"
console = ">=0.9.1, <1.0.0"
clap = "2.33"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
toml = "0.5.5"

